const Map<String, String> expenseLabelMapping = {
  'Education': '교육',
  'Transportation': '교통/자동차',
  'Other': '기타소비',
  'LargeMart': '대형마트',
  'Beauty': '미용',
  'Delivery': '배달',
  'Insurance': '보험',
  'DailyNecessities': '생필품',
  'LivingServices': '생활서비스',
  'TaxesAndFees': '세금/공과금',
  'ShoppingMall': '쇼핑몰',
  'TravelAndAccommodation': '여행/숙박',
  'DiningOut': '외식',
  'Healthcare': '의료/건강',
  'AlcoholAndPub': '주류/펍',
  'HobbiesAndLeisure': '취미/여가',
  'Cafe': '카페',
  'Communication': '통신',
  'ConvenienceStore': '편의점',
};
